### ISSUE TITLE
virustotal-api js > upload file, scan it & get the result

### ISSUE THREAD

**Issue by jerkdavi** [yousefvand/virustotal-api#5]
I have a js script that I can call, that uploads a file to virustotal for scanning, and returns the result of the scan.

    const fs = require("fs");
    const VirusTotalApi = require("virustotal-api");
    const virusTotal = new VirusTotalApi("<YOUR API KEY>");

    fs.readFile(__filename, (err, data) => {
      if (err) {
        console.log(`Cannot read file. ${err}`);
      } else {
        virusTotal
          .fileScan(data, "file.js")
          .then(response => {
            let resource = response.resource;
            // sometimes later try:
            virusTotal.fileReport(resource).then(result => {
              console.log(result);
            });
          })
          .catch(err => console.log(`Scan failed. ${err}`));
      }
    });

The only problem with it is that it returns this immediately after running.

    { response_code: -2,
    resource:
    '****************************************************************',
    scan_id:
    '****************************************************************',
    verbose_msg: 'Your resource is queued for analysis' }

So I have to keep calling it until after some time it completes and gives me the result. If I call it too quickly it returns this.

    (node:11475) UnhandledPromiseRejectionWarning: Error: Request rate limit exceeded. You are making more requests than allowed.
    at VirusTotal._checkResponse (/home/username/node_modules/virustotal-api/index.js:430:16)
    at VirusTotal.fileReport (/home/username/node_modules/virustotal-api/index.js:75:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    (node:11475) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    (node:11475) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Is there some way to get the result upon completion?

Or is there a way to pause the script at // sometimes later try:, make it wait 1 minute, and then return the result, hoping it will be done by then?

Thank you in advance.
Cheers.

**Comment by yousefvand** [comment]
> The only problem with it is that it returns this immediately after running.

You need to use a timer with a reasonable interval and upon call success disable the timer.

`const handle = setInterval(function() {/* sometimes later code */}, 60000)`

Above line runs `sometimes later code` every one minute and to stop timer use `clearInterval(handle)`.

> If I call it too quickly it returns this.

This is the nature of these kinds of REST APIs. Usually there are two types of accounts: free and premium. With free account you face `rate limit` when you call an API endpoint more than allowed times in an interval (for example more than ten requests per minute). If you hit rate limit you need to continue later.

As far as I know Virustotal doesn't accept `webhook`s so you need to check for the scan result yourself periodically (for example every five minutes).

You can check [my other project](https://github.com/yousefvand/virto-bot) which uses this library as a reference.

**Comment by jerkdavi** [comment]
Dear Remisa,

Thank you kindly for your response.
I have some further questions. How would I go about coding the part that upon call success disables the timer?
I am sorry, my questions are most probably dumb, and I do not expect you to code the entire thing for me.
Seeing as how you have far more knowledge than myself in the field, any reference to learning material would be of much value. :) 

I am sorry once again, and thank you once again.
David

**Comment by yousefvand** [comment]
Sample code for canceling timer.
```
let success = false;
let counter = 0;

const handle = setInterval(() => {
  console.log("We are trapped inside the timer");
  counter++;
  if (counter > 4) {
    success = true;
  }
  if (success) {
    clearInterval(handle);
    console.log("Timer is canceled");
  }
}, 1000);
```
I didn't have coding js for a while and you would better off asking programming questions on [https://stackoverflow.com/](https://stackoverflow.com/)

**Comment by jerkdavi** [comment]
Dear Remisa,
I posted my question on StackOverflow. You have been a great help nontheless, as you nudged me in the right direction, so thank you once more. :) 
Kindly,
David

**Comment by yousefvand** [comment]
You're welcome :tulip: :tulip: :tulip:
